export const desktopEn = {
  reenterPassword: "Re-enter password",
  passwordSource: "Password", enterPassword: "Enter and save a password", passwordPlaceholder: "Leave blank to ask when connecting", passwordSaveHint: "The password is encrypted in Vault when you save this desktop.", passwordStaged: "Password prepared. You can retry saving this desktop.", passwordSaveFailed: "Unable to prepare the password. Re-enter it and try again; this desktop has not been saved.", createVault: "Create Vault", unlockVault: "Unlock Vault", passwordVaultHint: "Unlock or create the local Vault to encrypt and save this desktop password.", passwordVaultFailed: "Unable to open Vault. Check your password and try again.", vaultMinimum: "Use at least 12 characters and confirm the Vault password. A forgotten Vault password cannot be recovered.",
  audioPlayback: "Play remote sound on this computer", audioPlaybackHint: "Applies to the next connection. Sound continues when switching tabs; mute it in the session toolbar.", muteAudio: "Mute remote sound", unmuteAudio: "Unmute remote sound", audioStates: { disabled: "Audio off", waiting: "Waiting for remote audio", ready: "Audio ready", unavailable: "Audio output unavailable", unsupported: "Remote audio format unsupported", closed: "Audio stopped" },
  navigation: "Remote", moreActions: "More actions",
  vaultCreate: "No local Vault exists. Create it now to continue this desktop connection.", vaultUnlock: "Unlock Vault to continue this desktop connection. Your Vault password stays in this protected window and Core.", vaultPassword: "Vault password", vaultPasswordConfirmation: "Confirm Vault password", editProfile: "Edit desktop",
  errors: { invalidConfiguration: "The saved connection is invalid.", authenticationRejected: "Authentication was rejected.", certificateRejected: "The target identity was not accepted.", unsupportedAuthentication: "This authentication method is unsupported.", unsupportedOperation: "This operation is unsupported by the protocol.", protocolError: "The desktop protocol failed.", resourceLimit: "The desktop resource limit was reached.", connectionLost: "The connection was lost.", timeout: "The operation timed out.", cancelled: "The operation was cancelled.", staleInput: "Desktop input ownership changed.", inputUncertain: "Input delivery is uncertain. It was not retried." },
  phases: { preparing: "Preparing", desktopConnecting: "Connecting to desktop", gatewayConnecting: "Connecting to SSH gateway", gatewayAuthenticating: "Authenticating SSH gateway", gatewayOpeningChannel: "Opening gateway connection", running: "Running" },
  title: "Remote desktop", newProfile: "New desktop", profiles: "Saved desktops", empty: "Connect to a remote desktop", emptyHint: "Save an RDP or VNC connection to get started.", edit: "Edit", delete: "Delete profile", save: "Save", cancel: "Cancel", connect: "Connect", disconnect: "Disconnect", reconnect: "Reconnect", close: "Close", refresh: "Refresh", label: "Name", protocol: "Protocol", address: "Address", port: "Port", username: "Username", domain: "Domain", gateway: "SSH gateway", direct: "Direct connection", credential: "Saved password", ask: "Ask securely when connecting", width: "Width", height: "Height", clipboard: "Enable text clipboard", clipboardHint: "The local clipboard is read or written only when you click Send or Receive.", sendClipboard: "Send clipboard", receiveClipboard: "Receive clipboard", fit: "Fit", actual: "100%", pan: "Pan desktop", fullscreen: "Fullscreen", focus: "Click the desktop to control it", panFocus: "Drag to pan the desktop", loading: "Loading…", error: "Unable to complete desktop operation", saved: "Desktop saved", deleted: "Profile deleted", clipboardDone: "Clipboard transferred", clipboardEmpty: "No remote clipboard text is available yet", invalid: "Enter a name, address, valid port and display size (200–8192).", confirmDelete: "Delete this saved desktop? Active sessions remain available.", failure: "The connection failed. Reconnect or close this session.", inputFailed: "Desktop input stopped. Click the desktop to acquire control again; input was not replayed.", secureTitle: "Remote desktop security", secureDescription: "Review this connection request in the protected window.", password: "Password", approve: "Approve this connection", reject: "Reject", fingerprint: "Fingerprint", algorithm: "Algorithm", certificate: "This certificate cannot automatically establish the server identity. Verify the target and full SHA-256 fingerprint through a trusted channel. Approval applies only to this connection.", hostKey: "Verify this SSH gateway identity before accepting it.", vncRisk: "This VNC connection does not encrypt the remote display or input. Continue only on a trusted network.", gatewayRisk: "SSH protects the connection to the gateway; the gateway-to-target segment is not encrypted by SSH.", credentials: "Credentials are used only for this connection.", answer: "Answer", done: "Decision submitted", states: { connecting: "Connecting", needsInteraction: "Waiting for approval", running: "Running", disconnecting: "Disconnecting", closed: "Disconnected", failed: "Failed" },
};
export const desktopZhCN: typeof desktopEn = {
  reenterPassword: "重新输入密码",
  passwordSource: "密码", enterPassword: "输入密码并保存", passwordPlaceholder: "留空则连接时输入", passwordSaveHint: "保存桌面时，密码将加密存入 Vault。", passwordStaged: "密码已准备，可以重试保存桌面配置。", passwordSaveFailed: "无法准备密码，请重新输入后重试；桌面尚未保存。", createVault: "创建 Vault", unlockVault: "解锁 Vault", passwordVaultHint: "请先解锁或创建本机 Vault，以加密保存此桌面密码。", passwordVaultFailed: "无法打开 Vault，请检查密码后重试。", vaultMinimum: "Vault 密码至少 12 个字符，并需再次确认；遗忘后无法恢复。",
  audioPlayback: "在本机播放远程声音", audioPlaybackHint: "下次连接生效。切换标签页后仍会播放，可在会话工具栏静音。", muteAudio: "静音远程声音", unmuteAudio: "取消远程静音", audioStates: { disabled: "声音已关闭", waiting: "等待远程音频", ready: "音频就绪", unavailable: "音频输出不可用", unsupported: "不支持远端音频格式", closed: "音频已停止" },
  navigation: "远程", moreActions: "更多操作",
  vaultCreate: "本机 Vault 未创建。请先创建，再继续本次桌面连接。", vaultUnlock: "解锁 Vault 后继续本次桌面连接。Vault 密码仅交给受保护窗口与 Core。", vaultPassword: "Vault 密码", vaultPasswordConfirmation: "确认 Vault 密码", editProfile: "编辑桌面",
  errors: { invalidConfiguration: "桌面配置无效。", authenticationRejected: "认证被拒绝。", certificateRejected: "目标身份未获接受。", unsupportedAuthentication: "不支持此认证方式。", unsupportedOperation: "此协议不支持该操作。", protocolError: "桌面协议交互失败。", resourceLimit: "已达到桌面资源限制。", connectionLost: "连接已丢失。", timeout: "操作超时。", cancelled: "操作已取消。", staleInput: "桌面输入控制权已变化。", inputUncertain: "输入送达状态不确定，未自动重试。" },
  phases: { preparing: "正在准备", desktopConnecting: "正在连接桌面", gatewayConnecting: "正在连接 SSH 网关", gatewayAuthenticating: "正在认证 SSH 网关", gatewayOpeningChannel: "正在打开网关连接", running: "运行中" },
  title: "远程桌面", newProfile: "新建桌面", profiles: "已保存桌面", empty: "连接远程桌面", emptyHint: "保存 RDP 或 VNC 连接，开始远程操作。", edit: "编辑", delete: "删除配置", save: "保存", cancel: "取消", connect: "连接", disconnect: "断开", reconnect: "重新连接", close: "关闭", refresh: "刷新", label: "名称", protocol: "协议", address: "地址", port: "端口", username: "用户名", domain: "域", gateway: "SSH 网关", direct: "直接连接", credential: "已保存密码", ask: "连接时在安全窗口输入", width: "宽度", height: "高度", clipboard: "启用文本剪贴板", clipboardHint: "仅在点击发送或接收时读写本机剪贴板。", sendClipboard: "发送剪贴板", receiveClipboard: "接收剪贴板", fit: "适应窗口", actual: "100%", pan: "拖动画面", fullscreen: "全屏", focus: "点击桌面以取得控制", panFocus: "拖拽以平移画面", loading: "正在加载…", error: "无法完成桌面操作", saved: "桌面已保存", deleted: "配置已删除", clipboardDone: "剪贴板已传输", clipboardEmpty: "远端暂时没有可接收的剪贴板文本", invalid: "请填写名称、地址、有效端口和显示尺寸（200–8192）。", confirmDelete: "删除此桌面配置？现有会话仍会保留。", failure: "连接失败，可重新连接或关闭此会话。", inputFailed: "桌面输入已停止。点击桌面重新取得控制；未重放输入。", secureTitle: "远程桌面安全确认", secureDescription: "请在受保护窗口中审阅本次连接请求。", password: "密码", approve: "批准本次连接", reject: "拒绝", fingerprint: "指纹", algorithm: "算法", certificate: "无法自动验证此证书的服务器身份。请通过可信渠道核对以下目标与完整 SHA-256 指纹；批准仅适用于本次连接。", hostKey: "接受前，请核对 SSH 网关身份。", vncRisk: "此 VNC 连接不加密远程画面或输入。仅在可信网络中继续。", gatewayRisk: "SSH 仅保护到网关的一段；网关到目标的一段不受 SSH 加密保护。", credentials: "凭据仅用于本次连接。", answer: "回答", done: "决定已提交", states: { connecting: "连接中", needsInteraction: "等待安全确认", running: "运行中", disconnecting: "正在断开", closed: "已断开", failed: "失败" },
};
