[package]
name = "norishell-ssh-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
bytes.workspace = true
norishell-ssh-domain = { path = "../ssh-domain" }
russh.workspace = true
russh-sftp.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeroize.workspace = true

[dev-dependencies]
rand.workspace = true
