import {
  Check,
  ChevronRight,
  CircleAlert,
  Clock3,
  Cloud,
  Code,
  Command,
  Copy,
  Download,
  Eye,
  Folder,
  Info,
  History,
  KeyRound,
  Link,
  LockKeyhole,
  LogOut,
  MoreHorizontal,
  Play,
  Plug,
  RefreshCw,
  Search,
  Server,
  Settings,
  Shield,
  Sparkles,
  StopCircle,
  Terminal,
  Upload,
  UserRound,
  X,
} from "lucide-vue-next";
import type { Component } from "vue";

export const pluginIconMap: Record<string, Component> = {
  terminal: Terminal,
  server: Server,
  folder: Folder,
  settings: Settings,
  plugin: Plug,
  command: Command,
  copy: Copy,
  search: Search,
  info: Info,
  check: Check,
  warning: CircleAlert,
  close: X,
  more: MoreHorizontal,
  play: Play,
  stop: StopCircle,
  refresh: RefreshCw,
  download: Download,
  upload: Upload,
  link: Link,
  shield: Shield,
  clock: Clock3,
  key: KeyRound,
  lock: LockKeyhole,
  cloud: Cloud,
  eye: Eye,
  chevronRight: ChevronRight,
  history: History,
  user: UserRound,
  logout: LogOut,
  sparkles: Sparkles,
  code: Code,
};
