//! Core-owned, one-command shell bootstraps for the session-only terminal
//! integration.  The decoded payload is never supplied by the renderer.

use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use norishell_core_api::NativeTerminalShellKind;

const BASH_SOURCE: &str = include_str!("native_terminal_scripts/bash.sh");
const ZSH_SOURCE: &str = include_str!("native_terminal_scripts/zsh.zsh");
const FISH_SOURCE: &str = include_str!("native_terminal_scripts/fish.fish");
const POWERSHELL_SOURCE: &str = include_str!("native_terminal_scripts/powershell.ps1");

/// Produces exactly one interactive-shell command followed by one carriage
/// return.  Keeping the payload encoded prevents a PTY from submitting each
/// source line as an independent interactive command.
pub(crate) fn script_for(
    shell: NativeTerminalShellKind,
    nonce: &str,
    capture_commands: bool,
) -> Vec<u8> {
    // `nonce` is generated by Core from `Uuid::now_v7`; keeping this check at
    // the rendering boundary prevents future callers from putting shell syntax
    // into an otherwise Core-owned bootstrap.
    assert!(
        !nonce.is_empty()
            && nonce
                .bytes()
                .all(|byte| byte.is_ascii_hexdigit() || byte == b'-'),
        "native-terminal nonce must be a UUID-shaped Core value"
    );

    let source = match shell {
        NativeTerminalShellKind::Bash => BASH_SOURCE,
        NativeTerminalShellKind::Zsh => ZSH_SOURCE,
        NativeTerminalShellKind::Fish => FISH_SOURCE,
        NativeTerminalShellKind::PowerShell => POWERSHELL_SOURCE,
    };
    let capture_mode = if capture_commands { "1" } else { "0" };
    let encoded = BASE64.encode(
        source
            .replace("__NORISHELL_NONCE__", nonce)
            .replace("__NORISHELL_CAPTURE_COMMAND__", capture_mode),
    );

    let command = match shell {
        // BSD base64 uses -D while GNU coreutils uses -d.  Repeat the encoded
        // value in the fallback so an option parser that consumed stdin before
        // failing cannot leave the second decoder with an empty stream.
        NativeTerminalShellKind::Bash => format!(
            "__norishell_bootstrap=1; eval \"$(printf %s '{encoded}' | base64 -d 2>/dev/null || printf %s '{encoded}' | base64 -D)\"; __norishell_bootstrap=0"
        ),
        NativeTerminalShellKind::Zsh => format!(
            "eval \"$(printf %s '{encoded}' | base64 -d 2>/dev/null || printf %s '{encoded}' | base64 -D)\""
        ),
        // `string collect` retains the decoded newlines as one argument, so
        // fish's eval parses the payload once instead of receiving one source
        // line per command-substitution element.
        NativeTerminalShellKind::Fish => format!(
            "eval (begin; printf %s '{encoded}' | base64 -d 2>/dev/null; or printf %s '{encoded}' | base64 -D; end | string collect)"
        ),
        NativeTerminalShellKind::PowerShell => format!(
            ". ([ScriptBlock]::Create([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('{encoded}'))))"
        ),
    };

    let mut bytes = command.into_bytes();
    bytes.push(b'\r');
    bytes
}

#[cfg(test)]
mod tests {
    use super::{BASE64, script_for};
    use base64::Engine as _;
    use norishell_core_api::NativeTerminalShellKind;

    const NONCE: &str = "123e4567-e89b-42d3-a456-426614174000";

    #[test]
    fn every_bootstrap_is_one_pty_command() {
        for shell in [
            NativeTerminalShellKind::Bash,
            NativeTerminalShellKind::Zsh,
            NativeTerminalShellKind::Fish,
            NativeTerminalShellKind::PowerShell,
        ] {
            let bytes = script_for(shell, NONCE, true);
            assert_eq!(bytes.last(), Some(&b'\r'));
            assert!(!bytes[..bytes.len() - 1].contains(&b'\r'));
            assert!(!bytes[..bytes.len() - 1].contains(&b'\n'));
        }
    }

    #[test]
    fn notification_bootstrap_selects_nontext_mode() {
        let cases = [
            (
                NativeTerminalShellKind::Bash,
                "__norishell_capture_command=0",
            ),
            (
                NativeTerminalShellKind::Zsh,
                "__norishell_capture_command=0",
            ),
            (
                NativeTerminalShellKind::Fish,
                "set -g __norishell_capture_command 0",
            ),
            (
                NativeTerminalShellKind::PowerShell,
                "$global:__NoriShellCaptureCommand = (0 -eq 1)",
            ),
        ];
        for (shell, expected_marker) in cases {
            let payload = decoded_payload(shell, false);
            assert!(
                payload.contains(expected_marker),
                "{shell:?} mode marker missing"
            );
            assert!(!payload.contains("__NORISHELL_CAPTURE_COMMAND__"));
        }
    }

    fn decoded_payload(shell: NativeTerminalShellKind, capture_commands: bool) -> String {
        let bytes = script_for(shell, NONCE, capture_commands);
        let command = std::str::from_utf8(&bytes[..bytes.len() - 1]).expect("UTF-8 bootstrap");
        let prefix = match shell {
            NativeTerminalShellKind::PowerShell => "FromBase64String('",
            _ => "printf %s '",
        };
        let encoded = command
            .split_once(prefix)
            .and_then(|(_, remainder)| remainder.split_once('\''))
            .map(|(encoded, _)| encoded)
            .expect("Core bootstrap contains its encoded payload");
        String::from_utf8(BASE64.decode(encoded).expect("valid Core payload"))
            .expect("UTF-8 shell source")
    }
}
