//! Stable, serializable types shared by the desktop Core and frontend.
//!
//! This crate deliberately contains no Tauri, database or platform execution code.

mod command;
mod desktop;
mod desktop_preferences;
mod tray;
pub use tray::*;
mod error;
mod forward_session;
mod host;
mod ids;
mod local_terminal;
mod native_terminal;
mod openssh_import;
mod plugin;
mod plugin_api;
mod plugin_app_integration;
mod plugin_approval_policy;
mod plugin_credential_api;
mod plugin_device_api;
mod plugin_dom;
mod plugin_file_api;
mod plugin_file_picker;
mod plugin_host;
mod plugin_isolated;
mod plugin_network_api;
mod plugin_operations;
mod plugin_process_api;
mod plugin_protocol;
mod plugin_remote_exec_api;
mod plugin_resources;
mod plugin_settings;
mod plugin_sftp_api;
mod plugin_special_permission;
mod plugin_ssh_sync_browser;
mod plugin_storage_api;
mod plugin_subscription_api;
mod plugin_terminal;
mod plugin_theme;
mod plugin_ui;
mod plugin_workflow;
mod server_overview;
mod sftp_session;
mod ssh_terminal;
mod telnet_terminal;
mod terminal_input;
mod terminal_workspace;
mod vault;
mod version;

pub use command::*;
pub use desktop::*;
pub use desktop_preferences::*;
pub use error::*;
pub use forward_session::*;
pub use host::*;
pub use ids::*;
pub use local_terminal::*;
pub use native_terminal::*;
pub use openssh_import::*;
pub use plugin::*;
pub use plugin_api::*;
pub use plugin_app_integration::*;
pub use plugin_approval_policy::*;
pub use plugin_credential_api::*;
pub use plugin_device_api::*;
pub use plugin_dom::*;
pub use plugin_file_api::*;
pub use plugin_file_picker::*;
pub use plugin_host::*;
pub use plugin_isolated::*;
pub use plugin_network_api::*;
pub use plugin_operations::*;
pub use plugin_process_api::*;
pub use plugin_protocol::*;
pub use plugin_remote_exec_api::*;
pub use plugin_resources::*;
pub use plugin_settings::*;
pub use plugin_sftp_api::*;
pub use plugin_special_permission::*;
pub use plugin_ssh_sync_browser::*;
pub use plugin_storage_api::*;
pub use plugin_subscription_api::*;
pub use plugin_terminal::*;
pub use plugin_theme::*;
pub use plugin_ui::*;
pub use plugin_workflow::*;
pub use server_overview::*;
pub use sftp_session::*;
pub use ssh_terminal::*;
pub use telnet_terminal::*;
pub use terminal_input::*;
pub use terminal_workspace::*;
pub use vault::*;
pub use version::*;

/// Wire command names are generated into TypeScript with the DTO declarations.
pub const COMMAND_HOST_LIST: &str = "host_list";
pub const COMMAND_HOST_CREATE: &str = "host_create";
pub const COMMAND_HOST_CONFIGURED_CREATE: &str = "host_configured_create";
pub const COMMAND_HOST_CREATE_PASSWORD_STAGE: &str = "host_create_password_stage";
pub const COMMAND_HOST_CREATE_PASSWORD_CANCEL: &str = "host_create_password_cancel";
pub const COMMAND_HOST_UPDATE: &str = "host_update";
pub const COMMAND_HOST_DELETE: &str = "host_delete";
pub const COMMAND_HOST_CATALOG_LIST: &str = "host_catalog_list";
pub const COMMAND_HOST_GROUP_LIST: &str = "host_group_list";
pub const COMMAND_HOST_GROUP_CREATE: &str = "host_group_create";
pub const COMMAND_HOST_GROUP_UPDATE: &str = "host_group_update";
pub const COMMAND_HOST_GROUP_DELETE: &str = "host_group_delete";
pub const COMMAND_HOST_TAG_LIST: &str = "host_tag_list";
pub const COMMAND_HOST_TAG_CREATE: &str = "host_tag_create";
pub const COMMAND_HOST_TAG_UPDATE: &str = "host_tag_update";
pub const COMMAND_HOST_TAG_DELETE: &str = "host_tag_delete";
pub const COMMAND_HOST_ORGANIZATION_GET: &str = "host_organization_get";
pub const COMMAND_HOST_ORGANIZATION_REPLACE: &str = "host_organization_replace";
pub const COMMAND_HOST_FAVORITE_UPDATE: &str = "host_favorite_update";
pub const COMMAND_RECENT_CONNECTION_LIST: &str = "recent_connection_list";
pub const COMMAND_HOST_CONNECTION_CONFIG_GET: &str = "host_connection_config_get";
pub const COMMAND_ROUTE_PLAN_REPLACE: &str = "route_plan_replace";
pub const COMMAND_AUTHENTICATION_PLAN_REPLACE: &str = "authentication_plan_replace";
pub const COMMAND_ALGORITHM_POLICY_CATALOG_GET: &str = "algorithm_policy_catalog_get";
pub const COMMAND_ALGORITHM_POLICY_REPLACE: &str = "algorithm_policy_replace";
pub const COMMAND_HEARTBEAT_POLICY_REPLACE: &str = "heartbeat_policy_replace";
pub const COMMAND_MONITORING_POLICY_REPLACE: &str = "monitoring_policy_replace";
pub const COMMAND_LOGIN_AUTOMATION_REPLACE: &str = "login_automation_replace";
pub const COMMAND_LOGIN_AUTOMATION_CONFIRM: &str = "login_automation_confirm";
pub const COMMAND_LOGIN_AUTOMATION_SECRET_CREATE: &str = "login_automation_secret_create";
pub const COMMAND_LOGIN_AUTOMATION_SECRET_CANCEL: &str = "login_automation_secret_cancel";
pub const COMMAND_IDENTITY_LIST: &str = "identity_list";
pub const COMMAND_IDENTITY_CREATE: &str = "identity_create";
pub const COMMAND_IDENTITY_UPDATE: &str = "identity_update";
pub const COMMAND_IDENTITY_DELETE_IMPACT: &str = "identity_delete_impact";
pub const COMMAND_IDENTITY_DELETE: &str = "identity_delete";
pub const COMMAND_CREDENTIAL_REF_LIST: &str = "credential_ref_list";
pub const COMMAND_CREDENTIAL_IMPORT: &str = "credential_import";
pub const COMMAND_PRIVATE_KEY_FILE_IMPORT: &str = "private_key_file_import";
pub const COMMAND_CREDENTIAL_TRANSIENT_PREPARE: &str = "credential_transient_prepare";
pub const COMMAND_SSH_AGENT_KEY_LIST: &str = "ssh_agent_key_list";
pub const COMMAND_SSH_AGENT_CREDENTIAL_CREATE: &str = "ssh_agent_credential_create";
pub const COMMAND_KEYBOARD_INTERACTIVE_CREDENTIAL_CREATE: &str =
    "keyboard_interactive_credential_create";
pub const COMMAND_OPENSSH_CONFIG_PREVIEW: &str = "openssh_config_preview";
pub const COMMAND_OPENSSH_CONFIG_COMMIT: &str = "openssh_config_commit";
pub const COMMAND_KNOWN_HOST_LIST: &str = "known_host_list";
pub const COMMAND_KNOWN_HOST_DELETE: &str = "known_host_delete";
pub const COMMAND_PLUGIN_INSTALLED_LIST: &str = "plugin_installed_list";
pub const COMMAND_PLUGIN_THEME_LIST: &str = "plugin_theme_list";
pub const COMMAND_PLUGIN_READINESS_GET: &str = "plugin_readiness_get";
pub const COMMAND_PLUGIN_AUDIT_LIST: &str = "plugin_audit_list";
pub const COMMAND_PLUGIN_SAFE_MODE_NEXT_START: &str = "plugin_safe_mode_next_start";
pub const COMMAND_PLUGIN_SAFE_MODE_STARTUP_COMPLETE: &str = "plugin_safe_mode_startup_complete";
pub const COMMAND_PLUGIN_LOCAL_INSTALL: &str = "plugin_local_install";
pub const COMMAND_PLUGIN_LOCAL_PACKAGE_PREPARE: &str = "plugin_local_package_prepare";
pub const COMMAND_PLUGIN_LOCAL_PACKAGE_CANCEL: &str = "plugin_local_package_cancel";
pub const COMMAND_PLUGIN_CAPABILITY_GRANTS_REPLACE: &str = "plugin_capability_grants_replace";
pub const COMMAND_PLUGIN_ENABLE: &str = "plugin_enable";
pub const COMMAND_PLUGIN_DISABLE: &str = "plugin_disable";
pub const COMMAND_PLUGIN_LOCALE_SET: &str = "plugin_locale_set";
pub const COMMAND_PLUGIN_UNINSTALL: &str = "plugin_uninstall";
pub const COMMAND_PLUGIN_OPERATION_GET: &str = "plugin_operation_get";
pub const COMMAND_PLUGIN_OPERATION_CANCEL: &str = "plugin_operation_cancel";
pub const COMMAND_PLUGIN_OPERATION_PERMISSIONS_LIST: &str = "plugin_operation_permissions_list";
pub const COMMAND_PLUGIN_OPERATION_PERMISSION_REVOKE: &str = "plugin_operation_permission_revoke";
pub const COMMAND_PLUGIN_OPERATION_PERMISSIONS_CLEAR: &str = "plugin_operation_permissions_clear";
pub const COMMAND_PLUGIN_CONTRIBUTION_LIST: &str = "plugin_contribution_list";
pub const COMMAND_PLUGIN_CONTRIBUTION_INVOKE: &str = "plugin_contribution_invoke";
pub const COMMAND_PLUGIN_CONTRIBUTION_COPY: &str = "plugin_contribution_copy";
pub const COMMAND_PLUGIN_EXTENSION_TARGET_LIST: &str = "plugin_extension_target_list";
pub const COMMAND_PLUGIN_TARGET_CONTEXT_OPEN: &str = "plugin_target_context_open";
pub const COMMAND_PLUGIN_TARGET_CONTEXT_CLOSE: &str = "plugin_target_context_close";
pub const COMMAND_PLUGIN_UI_CONTRIBUTION_LIST: &str = "plugin_ui_contribution_list";
pub const COMMAND_PLUGIN_UI_ACTION: &str = "plugin_ui_action";
pub const COMMAND_PLUGIN_SETTINGS_GET: &str = "plugin_settings_get";
pub const COMMAND_PLUGIN_SETTINGS_REPLACE: &str = "plugin_settings_replace";
pub const COMMAND_PLUGIN_SETTINGS_RESET: &str = "plugin_settings_reset";
pub const EVENT_PLUGIN_SETTINGS_CHANGED: &str = "plugin-settings-changed";
pub const COMMAND_PLUGIN_SSH_SYNC_BROWSER_READ: &str = "plugin_ssh_sync_browser_read";
pub const EVENT_PLUGIN_SSH_SYNC_BROWSER_INVALIDATED: &str = "plugin-ssh-sync-browser-invalidated";
pub const COMMAND_PLUGIN_NAVIGATION_LIST: &str = "plugin_navigation_list";
pub const COMMAND_PLUGIN_APP_INTEGRATION_LIST: &str = "plugin_app_integration_list";
pub const COMMAND_PLUGIN_HOST_SCOPE_LIST: &str = "plugin_host_scope_list";
pub const COMMAND_PLUGIN_HOST_SCOPE_REPLACE: &str = "plugin_host_scope_replace";
pub const COMMAND_PLUGIN_HOST_APPROVAL_OPEN: &str = "plugin_host_approval_open";
pub const COMMAND_PLUGIN_HOST_APPROVAL_GET: &str = "plugin_host_approval_get";
pub const COMMAND_PLUGIN_HOST_APPROVAL_DECIDE: &str = "plugin_host_approval_decide";
pub const COMMAND_PLUGIN_REMOTE_APPROVAL_GET: &str = "plugin_remote_approval_get";
pub const COMMAND_PLUGIN_CREDENTIAL_INPUT_SUBMIT: &str = "plugin_credential_input_submit";
pub const COMMAND_PLUGIN_REMOTE_APPROVAL_DECIDE: &str = "plugin_remote_approval_decide";
pub const COMMAND_PLUGIN_SPECIAL_PERMISSION_OPEN: &str = "plugin_special_permission_open";
pub const COMMAND_PLUGIN_SPECIAL_PERMISSION_GET: &str = "plugin_special_permission_get";
pub const COMMAND_PLUGIN_SPECIAL_PERMISSION_DECIDE: &str = "plugin_special_permission_decide";
pub const COMMAND_PLUGIN_ISOLATED_SURFACE_CONTENT: &str = "plugin_isolated_surface_content";
pub const COMMAND_PLUGIN_ISOLATED_BRIDGE: &str = "plugin_isolated_bridge";
pub const COMMAND_PLUGIN_TERMINAL_INPUT_PENDING_LIST: &str = "plugin_terminal_input_pending_list";
pub const COMMAND_PLUGIN_TERMINAL_INPUT_OPEN: &str = "plugin_terminal_input_open";
pub const COMMAND_PLUGIN_TERMINAL_INPUT_GET: &str = "plugin_terminal_input_get";
pub const COMMAND_PLUGIN_TERMINAL_INPUT_DECIDE: &str = "plugin_terminal_input_decide";
pub const COMMAND_PLUGIN_TERMINAL_OBSERVE_ATTACH: &str = "plugin_terminal_observe_attach";
pub const COMMAND_PLUGIN_TERMINAL_OBSERVE_DETACH: &str = "plugin_terminal_observe_detach";
pub const COMMAND_SERVER_OVERVIEW_SNAPSHOT: &str = "server_overview_snapshot";
pub const COMMAND_METRICS_RECONCILE: &str = "metrics_reconcile";
pub const COMMAND_METRICS_RETRY: &str = "metrics_retry";
pub const COMMAND_METRICS_STOP: &str = "metrics_stop";
pub const COMMAND_METRICS_HOST_KEY_DECIDE: &str = "metrics_host_key_decide";
pub const COMMAND_METRICS_KEYBOARD_INTERACTIVE_ANSWER_PREPARE: &str =
    "metrics_keyboard_interactive_answer_prepare";
pub const COMMAND_METRICS_KEYBOARD_INTERACTIVE_RESPOND: &str =
    "metrics_keyboard_interactive_respond";
pub const COMMAND_SSH_CONNECTION_TEST: &str = "ssh_connection_test";
pub const COMMAND_SSH_TERMINAL_OPEN: &str = "ssh_terminal_open";
pub const COMMAND_SSH_TERMINAL_SNAPSHOT: &str = "ssh_terminal_snapshot";
pub const COMMAND_SSH_TERMINAL_GET: &str = "ssh_terminal_get";
pub const COMMAND_SSH_TERMINAL_ATTACH: &str = "ssh_terminal_attach";
pub const COMMAND_SSH_TERMINAL_ATTACHMENT_HEARTBEAT: &str = "ssh_terminal_attachment_heartbeat";
pub const COMMAND_SSH_TERMINAL_DETACH: &str = "ssh_terminal_detach";
pub const COMMAND_SSH_TERMINAL_HOST_KEY_DECIDE: &str = "ssh_terminal_host_key_decide";
pub const COMMAND_SSH_TERMINAL_KEYBOARD_INTERACTIVE_ANSWER_PREPARE: &str =
    "ssh_terminal_keyboard_interactive_answer_prepare";
pub const COMMAND_SSH_TERMINAL_KEYBOARD_INTERACTIVE_RESPOND: &str =
    "ssh_terminal_keyboard_interactive_respond";
pub const COMMAND_SSH_TERMINAL_LOGIN_AUTOMATION_TAKEOVER: &str =
    "ssh_terminal_login_automation_takeover";
pub const COMMAND_SSH_TERMINAL_INPUT_FOCUS_SNAPSHOT: &str = "ssh_terminal_input_focus_snapshot";
pub const COMMAND_SSH_TERMINAL_INPUT_FOCUS_CHANGE: &str = "ssh_terminal_input_focus_change";
pub const COMMAND_SSH_TERMINAL_INPUT_LEASE_RENEW: &str = "ssh_terminal_input_lease_renew";
pub const COMMAND_SSH_TERMINAL_INPUT: &str = "ssh_terminal_input";
pub const COMMAND_SSH_TERMINAL_RESIZE: &str = "ssh_terminal_resize";
pub const COMMAND_SSH_TERMINAL_DISCONNECT: &str = "ssh_terminal_disconnect";
pub const COMMAND_SSH_TERMINAL_RECONNECT: &str = "ssh_terminal_reconnect";
pub const COMMAND_TERMINAL_INPUT_FOCUS_SNAPSHOT: &str = "terminal_input_focus_snapshot";
pub const COMMAND_TERMINAL_INPUT_FOCUS_CHANGE: &str = "terminal_input_focus_change";
pub const COMMAND_LOCAL_TERMINAL_OPEN: &str = "local_terminal_open";
pub const COMMAND_LOCAL_TERMINAL_SNAPSHOT: &str = "local_terminal_snapshot";
pub const COMMAND_LOCAL_TERMINAL_GET: &str = "local_terminal_get";
pub const COMMAND_LOCAL_TERMINAL_ATTACH: &str = "local_terminal_attach";
pub const COMMAND_LOCAL_TERMINAL_ATTACHMENT_HEARTBEAT: &str = "local_terminal_attachment_heartbeat";
pub const COMMAND_LOCAL_TERMINAL_DETACH: &str = "local_terminal_detach";
pub const COMMAND_LOCAL_TERMINAL_INPUT_LEASE_RENEW: &str = "local_terminal_input_lease_renew";
pub const COMMAND_LOCAL_TERMINAL_INPUT: &str = "local_terminal_input";
pub const COMMAND_LOCAL_TERMINAL_RESIZE: &str = "local_terminal_resize";
pub const COMMAND_LOCAL_TERMINAL_TERMINATE: &str = "local_terminal_terminate";
pub const COMMAND_NATIVE_TERMINAL_SETTINGS_GET: &str = "native_terminal_settings_get";
pub const COMMAND_NATIVE_TERMINAL_SETTINGS_REPLACE: &str = "native_terminal_settings_replace";
pub const COMMAND_NATIVE_TERMINAL_ENABLE: &str = "native_terminal_enable";
pub const COMMAND_NATIVE_TERMINAL_SNAPSHOT: &str = "native_terminal_snapshot";
pub const COMMAND_NATIVE_TERMINAL_HISTORY_LIST: &str = "native_terminal_history_list";
pub const COMMAND_NATIVE_TERMINAL_HISTORY_DELETE: &str = "native_terminal_history_delete";
pub const COMMAND_NATIVE_TERMINAL_HISTORY_CLEAR: &str = "native_terminal_history_clear";
pub const COMMAND_NATIVE_TERMINAL_HISTORY_PAUSE: &str = "native_terminal_history_pause";
pub const COMMAND_DESKTOP_PREFERENCES_GET: &str = "desktop_preferences_get";
pub const COMMAND_DESKTOP_PREFERENCES_REPLACE: &str = "desktop_preferences_replace";
pub const COMMAND_TELNET_TERMINAL_OPEN: &str = "telnet_terminal_open";
pub const COMMAND_TELNET_TERMINAL_SNAPSHOT: &str = "telnet_terminal_snapshot";
pub const COMMAND_TELNET_TERMINAL_ATTACH: &str = "telnet_terminal_attach";
pub const COMMAND_TELNET_TERMINAL_ATTACHMENT_HEARTBEAT: &str =
    "telnet_terminal_attachment_heartbeat";
pub const COMMAND_TELNET_TERMINAL_DETACH: &str = "telnet_terminal_detach";
pub const COMMAND_TELNET_TERMINAL_INPUT_LEASE_RENEW: &str = "telnet_terminal_input_lease_renew";
pub const COMMAND_TELNET_TERMINAL_INPUT: &str = "telnet_terminal_input";
pub const COMMAND_TELNET_TERMINAL_RESIZE: &str = "telnet_terminal_resize";
pub const COMMAND_TELNET_TERMINAL_DISCONNECT: &str = "telnet_terminal_disconnect";
pub const COMMAND_TELNET_TERMINAL_RECONNECT: &str = "telnet_terminal_reconnect";
pub const COMMAND_FORWARD_RULE_LIST: &str = "forward_rule_list";
pub const COMMAND_FORWARD_RULE_CREATE: &str = "forward_rule_create";
pub const COMMAND_FORWARD_RULE_UPDATE: &str = "forward_rule_update";
pub const COMMAND_FORWARD_RULE_DELETE: &str = "forward_rule_delete";
pub const COMMAND_FORWARD_RULE_PREFLIGHT: &str = "forward_rule_preflight";
pub const COMMAND_FORWARD_SESSION_START: &str = "forward_session_start";
pub const COMMAND_FORWARD_SESSION_SNAPSHOT: &str = "forward_session_snapshot";
pub const COMMAND_FORWARD_SESSION_STOP: &str = "forward_session_stop";
pub const COMMAND_FORWARD_CLEANUP_RETAIN: &str = "forward_cleanup_retain";
pub const COMMAND_SFTP_SESSION_OPEN: &str = "sftp_session_open";
pub const COMMAND_SFTP_SESSION_SNAPSHOT: &str = "sftp_session_snapshot";
pub const COMMAND_SFTP_SESSION_DISCONNECT: &str = "sftp_session_disconnect";
pub const COMMAND_SFTP_LOCAL_BOUNDARY_REGISTER: &str = "sftp_local_boundary_register";
pub const COMMAND_SFTP_LOCAL_DIRECTORY_REGISTER: &str = "sftp_local_directory_register";
pub const COMMAND_SFTP_LOCAL_DIRECTORY_LIST: &str = "sftp_local_directory_list";
pub const COMMAND_SFTP_LOCAL_DIRECTORY_OPEN_CHILD: &str = "sftp_local_directory_open_child";
pub const COMMAND_SFTP_LOCAL_DIRECTORY_CREATE_CHILD: &str = "sftp_local_directory_create_child";
pub const COMMAND_SFTP_LOCAL_DIRECTORY_RELEASE: &str = "sftp_local_directory_release";
pub const COMMAND_SFTP_DIRECTORY_LIST: &str = "sftp_directory_list";
pub const COMMAND_SFTP_DIRECTORY_LIST_CANCEL: &str = "sftp_directory_list_cancel";
pub const COMMAND_SFTP_FILE_PREVIEW: &str = "sftp_file_preview";
pub const COMMAND_SFTP_FILE_TAIL: &str = "sftp_file_tail";
pub const COMMAND_SFTP_FILE_MUTATE: &str = "sftp_file_mutate";
pub const COMMAND_SFTP_TRANSFER_ENQUEUE: &str = "sftp_transfer_enqueue";
pub const COMMAND_SFTP_TRANSFER_INTENT_PREPARE: &str = "sftp_transfer_intent_prepare";
pub const COMMAND_SFTP_TRANSFER_INTENT_ENQUEUE: &str = "sftp_transfer_intent_enqueue";
pub const COMMAND_SFTP_TRANSFER_INTENT_SNAPSHOT: &str = "sftp_transfer_intent_snapshot";
pub const COMMAND_SFTP_TRANSFER_INTENT_CANCEL: &str = "sftp_transfer_intent_cancel";
pub const COMMAND_SFTP_TRANSFER_INTENT_CLEANUP_RETRY: &str = "sftp_transfer_intent_cleanup_retry";
pub const COMMAND_SFTP_TRANSFER_INTENT_CLEANUP_RETAIN: &str = "sftp_transfer_intent_cleanup_retain";
pub const COMMAND_SFTP_TRANSFER_CANCEL: &str = "sftp_transfer_cancel";
pub const COMMAND_SFTP_TRANSFER_RESUME: &str = "sftp_transfer_resume";
pub const COMMAND_SFTP_REMOTE_CLEANUP_RETRY: &str = "sftp_remote_cleanup_retry";
pub const COMMAND_SFTP_REMOTE_CLEANUP_RETAIN: &str = "sftp_remote_cleanup_retain";
pub const COMMAND_TERMINAL_WORKSPACE_LAYOUT_GET: &str = "terminal_workspace_layout_get";
pub const COMMAND_TERMINAL_WORKSPACE_LAYOUT_REPLACE: &str = "terminal_workspace_layout_replace";
pub const COMMAND_VAULT_STATUS: &str = "vault_status";
pub const COMMAND_VAULT_CREATE: &str = "vault_create";
pub const COMMAND_VAULT_UNLOCK: &str = "vault_unlock";
pub const COMMAND_VAULT_LOCK: &str = "vault_lock";
pub const COMMAND_VAULT_AUTO_UNLOCK_ENABLE: &str = "vault_auto_unlock_enable";
pub const COMMAND_VAULT_AUTO_UNLOCK_DISABLE: &str = "vault_auto_unlock_disable";
pub const COMMAND_VAULT_CHANGE_PASSWORD: &str = "vault_change_password";
pub const COMMAND_WINDOW_REQUEST_CLOSE: &str = "window_request_close";
pub const COMMAND_APPLICATION_REQUEST_EXIT: &str = "application_request_exit";
pub const COMMAND_TRAY_ACTION_TAKE: &str = "tray_action_take";
pub const COMMAND_TRAY_ACTIONS_READY: &str = "tray_actions_ready";
pub const COMMAND_TRAY_PANEL_SNAPSHOT: &str = "tray_panel_snapshot";
pub const COMMAND_TRAY_PANEL_EXECUTE: &str = "tray_panel_execute";
pub const COMMAND_TRAY_PANEL_HIDE: &str = "tray_panel_hide";

mod plugin_protocol_launch;
pub use plugin_protocol_launch::*;

mod plugin_terminal_session;
pub use plugin_terminal_session::*;

pub const COMMAND_PLUGIN_PROTOCOL_LAUNCH_LIST: &str = "plugin_protocol_launch_list";
pub const COMMAND_PLUGIN_PROTOCOL_LAUNCH_CLAIM: &str = "plugin_protocol_launch_claim";
pub const COMMAND_PLUGIN_TERMINAL_OPEN: &str = "plugin_terminal_open";
pub const COMMAND_PLUGIN_TERMINAL_SNAPSHOT: &str = "plugin_terminal_snapshot";
pub const COMMAND_PLUGIN_TERMINAL_ATTACH: &str = "plugin_terminal_attach";
pub const COMMAND_PLUGIN_TERMINAL_ATTACHMENT_HEARTBEAT: &str =
    "plugin_terminal_attachment_heartbeat";
pub const COMMAND_PLUGIN_TERMINAL_DETACH: &str = "plugin_terminal_detach";
pub const COMMAND_PLUGIN_TERMINAL_INPUT_LEASE_RENEW: &str = "plugin_terminal_input_lease_renew";
pub const COMMAND_PLUGIN_TERMINAL_INPUT: &str = "plugin_terminal_input";
pub const COMMAND_PLUGIN_TERMINAL_RESIZE: &str = "plugin_terminal_resize";
pub const COMMAND_PLUGIN_TERMINAL_DISCONNECT: &str = "plugin_terminal_disconnect";
pub const COMMAND_PLUGIN_TERMINAL_RECONNECT: &str = "plugin_terminal_reconnect";
