//! Bounded, Core-owned plugin workflow wire types.
//!
//! A workflow catalog is immutable package metadata. It names the only step
//! identifiers a running Wasm instance may use, but it is deliberately not an
//! executable plan and grants no capability. The actual next API call is
//! produced one event at a time by the running plugin instance and brokered by
//! Core.

use std::{collections::BTreeMap, fmt, str::FromStr};

use serde::{Deserialize, Deserializer, Serialize, Serializer, de};
use ts_rs::TS;
use uuid::{Uuid, Version};

use crate::{
    PluginApiCall, PluginApiOperation, PluginApiReply, PluginApiResourceEvent, PluginId,
    PluginSettingLabel, RequestMeta, WireSequence,
};

pub const PLUGIN_WORKFLOW_CATALOG_SCHEMA_VERSION: u16 = 1;
pub const MAX_PLUGIN_WORKFLOWS: usize = 8;
pub const MAX_PLUGIN_WORKFLOW_STEPS: usize = 8;
pub const MAX_PLUGIN_WORKFLOW_ID_BYTES: usize = 64;
pub const MAX_PLUGIN_WORKFLOW_INPUT_BYTES: usize = 64 * 1024;
pub const MAX_PLUGIN_WORKFLOW_FILE_SCOPE_HANDLES: usize = 32;
pub const MAX_PLUGIN_WORKFLOW_EVENTS: usize = 64;
pub const MAX_PLUGIN_WORKFLOW_RESULT_BYTES: usize = 2 * 1024 * 1024;

/// UUIDv7 generated by Core for one workflow task. It is a correlation value,
/// not an authorization token.
#[derive(Debug, Clone, PartialEq, Eq, Hash, TS)]
#[ts(type = "string")]
pub struct PluginWorkflowTaskId(String);

impl PluginWorkflowTaskId {
    pub fn parse(value: impl Into<String>) -> Result<Self, &'static str> {
        let value = value.into();
        let parsed =
            Uuid::parse_str(&value).map_err(|_| "plugin_workflow_task_id must be UUIDv7")?;
        if parsed.get_version() != Some(Version::SortRand) {
            return Err("plugin_workflow_task_id must be UUIDv7");
        }
        Ok(Self(parsed.to_string()))
    }

    #[must_use]
    #[cfg(not(target_arch = "wasm32"))]
    pub fn new() -> Self {
        Self(Uuid::now_v7().to_string())
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl Default for PluginWorkflowTaskId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for PluginWorkflowTaskId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl FromStr for PluginWorkflowTaskId {
    type Err = &'static str;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::parse(value)
    }
}

impl Serialize for PluginWorkflowTaskId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for PluginWorkflowTaskId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Self::parse(String::deserialize(deserializer)?).map_err(de::Error::custom)
    }
}

/// Fixed package metadata loaded only from `assets/workflows.json`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowCatalog {
    pub schema_version: u16,
    pub workflows: Vec<PluginWorkflowDefinition>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowDefinition {
    pub id: String,
    pub label: PluginSettingLabel,
    pub steps: Vec<PluginWorkflowStepDefinition>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowStepDefinition {
    pub id: String,
    pub label: PluginSettingLabel,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub enum PluginWorkflowTaskState {
    Running,
    Dispatching,
    NeedsUserAction,
    Cancelling,
    Cancelled,
    Completed,
    Failed,
    Interrupted,
    CleanupIncomplete,
}

impl PluginWorkflowTaskState {
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::Cancelled
                | Self::Completed
                | Self::Failed
                | Self::Interrupted
                | Self::CleanupIncomplete
        )
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub enum PluginWorkflowStepState {
    Dispatching,
    Succeeded,
    Failed,
    NeedsUserAction,
    OutcomeUnknown,
    Interrupted,
}

/// The safe operation name stored with one step. It contains no call
/// arguments, target, URL, command, request body, or secret-derived digest.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
pub enum PluginWorkflowApiMethod {
    SerialDevices,
    SerialOpen,
    SerialSend,
    ProtocolOpen,
    Describe,
    Permissions,
    PermissionRequest,
    PermissionRevoke,
    PermissionsForget,
    ResourcesList,
    ResourceClose,
    SubscriptionStart,
    TimerStart,
    ResourceEvents,
    NetworkStart,
    NetworkSend,
    RemoteExecStart,
    RemoteExecSend,
    ProcessStart,
    ProcessSend,
    SftpOpen,
    Sftp,
    FilePick,
    File,
    Credential,
    Storage,
    TerminalRequestInput,
}

impl PluginWorkflowApiMethod {
    #[must_use]
    #[allow(unreachable_patterns)] // future host-only operations deliberately map to None.
    pub const fn from_operation(operation: &PluginApiOperation) -> Option<Self> {
        Some(match operation {
            PluginApiOperation::SerialDevices { .. } => Self::SerialDevices,
            PluginApiOperation::SerialOpen { .. } => Self::SerialOpen,
            PluginApiOperation::SerialSend { .. } => Self::SerialSend,
            PluginApiOperation::ProtocolOpen { .. } => Self::ProtocolOpen,
            PluginApiOperation::Describe { .. } => Self::Describe,
            PluginApiOperation::Permissions { .. } => Self::Permissions,
            PluginApiOperation::PermissionRequest { .. } => Self::PermissionRequest,
            PluginApiOperation::PermissionRevoke { .. } => Self::PermissionRevoke,
            PluginApiOperation::PermissionsForget { .. } => Self::PermissionsForget,
            PluginApiOperation::ResourcesList { .. } => Self::ResourcesList,
            PluginApiOperation::ResourceClose { .. } => Self::ResourceClose,
            PluginApiOperation::SubscriptionStart { .. } => Self::SubscriptionStart,
            PluginApiOperation::TimerStart { .. } => Self::TimerStart,
            PluginApiOperation::ResourceEvents { .. } => Self::ResourceEvents,
            PluginApiOperation::NetworkStart { .. } => Self::NetworkStart,
            PluginApiOperation::NetworkSend { .. } => Self::NetworkSend,
            PluginApiOperation::RemoteExecStart { .. } => Self::RemoteExecStart,
            PluginApiOperation::RemoteExecSend { .. } => Self::RemoteExecSend,
            PluginApiOperation::ProcessStart { .. } => Self::ProcessStart,
            PluginApiOperation::ProcessSend { .. } => Self::ProcessSend,
            PluginApiOperation::SftpOpen { .. } => Self::SftpOpen,
            PluginApiOperation::Sftp { .. } => Self::Sftp,
            PluginApiOperation::FilePick { .. } => Self::FilePick,
            PluginApiOperation::File { .. } => Self::File,
            PluginApiOperation::Credential { .. } => Self::Credential,
            PluginApiOperation::Storage { .. } => Self::Storage,
            PluginApiOperation::TerminalRequestInput { .. } => Self::TerminalRequestInput,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskSummary {
    pub task_id: PluginWorkflowTaskId,
    pub plugin_id: PluginId,
    pub workflow_id: String,
    pub state: PluginWorkflowTaskState,
    pub revision: WireSequence,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub current_step_id: Option<String>,
    pub outcome_unknown: bool,
    pub cleanup_incomplete: bool,
    #[ts(type = "number")]
    pub created_at_unix_ms: i64,
    #[ts(type = "number")]
    pub updated_at_unix_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskStepSummary {
    pub step_id: String,
    pub method: PluginWorkflowApiMethod,
    pub state: PluginWorkflowStepState,
    pub revision: WireSequence,
    pub outcome_unknown: bool,
    #[ts(type = "number")]
    pub created_at_unix_ms: i64,
    #[ts(type = "number")]
    pub updated_at_unix_ms: i64,
}

/// Replies are deliberately retained only in the current process. The task
/// repository never serializes this type into SQLite.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskResult {
    pub task_id: PluginWorkflowTaskId,
    pub replies: Vec<PluginApiReply>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskSnapshot {
    pub task: PluginWorkflowTaskSummary,
    pub steps: Vec<PluginWorkflowTaskStepSummary>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub result: Option<PluginWorkflowTaskResult>,
}

/// This request may carry package-defined JSON input only in process memory.
/// It must never be logged, persisted, fingerprinted, or replayed after a
/// restart.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskStartRequest {
    pub meta: RequestMeta,
    pub plugin_id: PluginId,
    #[serde(rename = "artifactFingerprintSha256")]
    pub signer_fingerprint_sha256: String,
    pub expected_package_sha256: String,
    pub expected_state_version: WireSequence,
    pub instance_generation: WireSequence,
    pub workflow_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub input_json: Option<String>,
    /// Opaque, Core-issued file root handles selected before an explicit task
    /// start. Core adopts them into the task consumer and gives the Wasm
    /// instance only the old-to-new handle map in its in-memory start event.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub file_scope_handles: Vec<String>,
}

impl fmt::Debug for PluginWorkflowTaskStartRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("PluginWorkflowTaskStartRequest")
            .field("request_id", &self.meta.request_id)
            .field("plugin_id", &self.plugin_id)
            .field("workflow_id", &self.workflow_id)
            .field(
                "input_json",
                &self
                    .input_json
                    .as_ref()
                    .map(|value| format!("[REDACTED; {} bytes]", value.len())),
            )
            .field(
                "file_scope_handles",
                &format_args!("[OPAQUE; {} handles]", self.file_scope_handles.len()),
            )
            .finish_non_exhaustive()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskGetRequest {
    pub meta: RequestMeta,
    pub task_id: PluginWorkflowTaskId,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskListRequest {
    pub meta: RequestMeta,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub plugin_id: Option<PluginId>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskCancelRequest {
    pub meta: RequestMeta,
    pub task_id: PluginWorkflowTaskId,
    pub expected_revision: WireSequence,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowTaskResumeRequest {
    pub meta: RequestMeta,
    pub task_id: PluginWorkflowTaskId,
    pub expected_revision: WireSequence,
}

/// Core sends this bounded event to the same in-process Wasm instance. The
/// event is never read from SQLite and must not be replayed after restart.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(
    tag = "kind",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum WorkflowEvent {
    Start {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        #[ts(optional)]
        input_json: Option<String>,
        /// Opaque source-to-task root handle mapping. It exists only for this
        /// in-process start event and is never persisted or replayed.
        #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
        file_scopes: BTreeMap<String, String>,
    },
    StepResult {
        step_id: String,
        reply: PluginApiReply,
    },
    ResourceEvents {
        handle: String,
        events: Vec<PluginApiResourceEvent>,
        backpressured: bool,
    },
}

impl fmt::Debug for WorkflowEvent {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Start {
                input_json,
                file_scopes,
            } => formatter
                .debug_struct("WorkflowEvent::Start")
                .field(
                    "input_json",
                    &input_json
                        .as_ref()
                        .map(|value| format!("[REDACTED; {} bytes]", value.len())),
                )
                .field(
                    "file_scopes",
                    &format_args!("[OPAQUE; {} handles]", file_scopes.len()),
                )
                .finish(),
            Self::StepResult { step_id, .. } => formatter
                .debug_struct("WorkflowEvent::StepResult")
                .field("step_id", step_id)
                .field("reply", &"[REDACTED]")
                .finish(),
            Self::ResourceEvents {
                handle,
                events,
                backpressured,
            } => formatter
                .debug_struct("WorkflowEvent::ResourceEvents")
                .field("handle", handle)
                .field("event_count", &events.len())
                .field("backpressured", backpressured)
                .finish(),
        }
    }
}

/// A Wasm workflow transition. Core accepts at most one typed API call for
/// the requested fixed step, then gives its reply back as a later event.
/// With neither a call nor completion, Core waits for an already-owned resource event.
/// Waiting without any task resource is rejected instead of leaving an inert task running.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkflowResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub step_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub call: Option<PluginApiCall>,
    pub complete: bool,
}

/// One Core-correlated request to the resident Wasm workflow handler.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PluginWorkflowEvent {
    pub task_id: PluginWorkflowTaskId,
    pub workflow_id: String,
    pub event: WorkflowEvent,
}

impl fmt::Debug for WorkflowResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("WorkflowResponse")
            .field("step_id", &self.step_id)
            .field("call", &self.call.as_ref().map(|_| "[REDACTED]"))
            .field("complete", &self.complete)
            .finish()
    }
}

#[must_use]
pub fn valid_plugin_workflow_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= MAX_PLUGIN_WORKFLOW_ID_BYTES
        && value.is_ascii()
        && value
            .bytes()
            .next()
            .is_some_and(|byte| byte.is_ascii_alphanumeric())
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn workflow_ids_are_bounded_ascii_identifiers() {
        assert!(valid_plugin_workflow_id("backup.daily"));
        assert!(valid_plugin_workflow_id("A_1-step"));
        assert!(!valid_plugin_workflow_id(""));
        assert!(!valid_plugin_workflow_id(".leading"));
        assert!(!valid_plugin_workflow_id("contains space"));
        assert!(!valid_plugin_workflow_id(&"a".repeat(65)));
    }
}
